import React from 'react';
import { FinalConsensusReport } from '../services/debateEngine';
import { ShieldAlert, CheckCircle2, Download, FileText, Sparkles, Award } from 'lucide-react';

interface ConsensusReportViewProps {
  report: FinalConsensusReport;
}

export const ConsensusReportView: React.FC<ConsensusReportViewProps> = ({ report }) => {

  const exportMarkdown = () => {
    const content = `# ALVO 2.0 Research & Consensus Report

**Topic:** ${report.topic}
**Consensus Score:** ${report.consensusScore}%

---

## Executive Summary
${report.executiveSummary}

## Core Agreements
${report.coreAgreements.map(a => `- ${a}`).join('\n')}

## Major Friction Points
${report.majorFrictionPoints.map(f => `- ${f}`).join('\n')}

## Risk & Mitigation Matrix
${report.riskMatrix.map(r => `### [${r.severity}] ${r.risk}\n- **Mitigation:** ${r.mitigation}`).join('\n\n')}

## Final Strategic Verdict
${report.finalVerdict}

---
*Generated by ALVO 2.0 Autonomous 50-AI Research Engine*
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ALVO_Research_${report.topic.slice(0, 20).replace(/\s+/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportJSON = () => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ALVO_Research_${report.topic.slice(0, 20).replace(/\s+/g, '_')}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-gradient-to-br from-cyber-card via-[#0f1420] to-[#090b10] border border-cyan-500/40 rounded-2xl p-6 shadow-[0_0_50px_rgba(0,240,255,0.2)] space-y-6">
      
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-cyber-border">
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-2xl bg-cyan-500/10 border border-cyan-500/30 text-cyan-400">
            <Award className="w-7 h-7" />
          </div>
          <div>
            <h2 className="font-extrabold text-xl text-white font-sans tracking-wide">
              SYNTHESIZED CONSENSUS & RESEARCH REPORT
            </h2>
            <p className="text-xs text-gray-400 font-mono mt-0.5">
              Topic: "{report.topic}"
            </p>
          </div>
        </div>

        {/* Score Badge & Download Buttons */}
        <div className="flex items-center gap-3 w-full sm:w-auto justify-between sm:justify-end">
          <div className="flex items-center gap-2 px-4 py-2 rounded-xl bg-cyan-950/60 border border-cyan-500/40 text-cyan-300 font-mono">
            <span className="text-xs text-gray-400">Consensus:</span>
            <span className="text-lg font-bold text-cyan-400">{report.consensusScore}%</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={exportMarkdown}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-cyber-card hover:bg-cyber-card/80 border border-cyber-border text-xs font-semibold text-gray-200 hover:text-white transition"
              title="Export Markdown"
            >
              <FileText className="w-4 h-4 text-cyan-400" /> Export .MD
            </button>
            <button
              onClick={exportJSON}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-cyber-card hover:bg-cyber-card/80 border border-cyber-border text-xs font-semibold text-gray-200 hover:text-white transition"
              title="Export JSON"
            >
              <Download className="w-4 h-4 text-purple-400" /> Export JSON
            </button>
          </div>
        </div>
      </div>

      {/* Executive Summary */}
      <div className="bg-[#090b10]/80 p-4 rounded-xl border border-cyber-border/80">
        <h4 className="text-xs font-mono font-bold text-cyan-400 uppercase tracking-wider mb-1.5">
          Executive Summary
        </h4>
        <p className="text-sm text-gray-200 leading-relaxed font-sans">
          {report.executiveSummary}
        </p>
      </div>

      {/* Core Agreements & Friction Points Split Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        
        {/* Core Agreements */}
        <div className="bg-emerald-950/20 border border-emerald-500/30 p-4 rounded-xl">
          <h4 className="flex items-center gap-2 text-xs font-mono font-bold text-emerald-400 uppercase tracking-wider mb-2">
            <CheckCircle2 className="w-4 h-4" /> Key Consensus Agreements
          </h4>
          <ul className="space-y-2">
            {report.coreAgreements.map((item, idx) => (
              <li key={idx} className="flex items-start gap-2 text-xs text-emerald-200 leading-relaxed font-sans">
                <span className="text-emerald-400 font-bold">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Friction Points */}
        <div className="bg-rose-950/20 border border-rose-500/30 p-4 rounded-xl">
          <h4 className="flex items-center gap-2 text-xs font-mono font-bold text-rose-400 uppercase tracking-wider mb-2">
            <ShieldAlert className="w-4 h-4" /> Primary Friction Points & Divergences
          </h4>
          <ul className="space-y-2">
            {report.majorFrictionPoints.map((item, idx) => (
              <li key={idx} className="flex items-start gap-2 text-xs text-rose-200 leading-relaxed font-sans">
                <span className="text-rose-400 font-bold">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

      </div>

      {/* Risk & Mitigation Matrix */}
      <div className="space-y-2">
        <h4 className="text-xs font-mono font-bold text-amber-400 uppercase tracking-wider">
          Risk & Mitigation Matrix
        </h4>
        <div className="border border-cyber-border rounded-xl overflow-hidden bg-[#090b10]">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="bg-cyber-card/80 border-b border-cyber-border text-gray-400 font-mono">
                <th className="p-3">Risk Factor</th>
                <th className="p-3 w-28">Severity</th>
                <th className="p-3">Strategic Mitigation</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-cyber-border/60">
              {report.riskMatrix.map((r, idx) => (
                <tr key={idx} className="hover:bg-cyber-card/40 transition">
                  <td className="p-3 font-semibold text-gray-200">{r.risk}</td>
                  <td className="p-3">
                    <span
                      className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold ${
                        r.severity === 'High'
                          ? 'bg-rose-500/20 text-rose-300 border border-rose-500/40'
                          : r.severity === 'Medium'
                          ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                          : 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                      }`}
                    >
                      {r.severity}
                    </span>
                  </td>
                  <td className="p-3 text-gray-300">{r.mitigation}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Final Strategic Verdict */}
      <div className="bg-gradient-to-r from-purple-950/40 via-cyan-950/40 to-purple-950/40 border border-purple-500/40 p-4.5 rounded-xl shadow-[0_0_20px_rgba(157,0,255,0.15)]">
        <h4 className="flex items-center gap-2 text-xs font-mono font-bold text-purple-300 uppercase tracking-wider mb-1.5">
          <Sparkles className="w-4 h-4 text-cyan-400" /> Final Strategic Verdict & Recommendation
        </h4>
        <p className="text-sm font-semibold text-white leading-relaxed font-sans">
          {report.finalVerdict}
        </p>
      </div>

    </div>
  );
};
